baseURL = "https://kevba.com/"
languageCode = "en-us"
title = "Kevba's Blog"
theme = "hugo_theme_pickles"

[params]
  github = "kevba"

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
